//Generated by premake! Add and/or remove any nessesary includes here!
//Do not remove unless you want to regenerate the default precompile header!
#pragma once

#define NOMINMAX

//Libary Links
#ifdef _DEBUG
#pragma comment(lib, "..\\vendor\\source\\fbx_sdk\\2020.3.2\\lib\\vs2019\\x64\\debug\\libfbxsdk-md.lib")
#pragma comment(lib, "..\\vendor\\source\\fbx_sdk\\2020.3.2\\lib\\vs2019\\x64\\debug\\libxml2-md.lib")
#pragma comment(lib, "..\\vendor\\source\\fbx_sdk\\2020.3.2\\lib\\vs2019\\x64\\debug\\zlib-md.lib")
#else
#pragma comment(lib, "..\\vendor\\source\\fbx_sdk\\2020.3.2\\lib\\vs2019\\x64\\release\\libfbxsdk-md.lib")
#pragma comment(lib, "..\\vendor\\source\\fbx_sdk\\2020.3.2\\lib\\vs2019\\x64\\release\\libxml2-md.lib")
#pragma comment(lib, "..\\vendor\\source\\fbx_sdk\\2020.3.2\\lib\\vs2019\\x64\\release\\zlib-md.lib")
#endif

//Standard Library includes
#include <filesystem>
#include <iostream>
#include <string>
#include <string_view>
#include <cmath>
#include <functional>
#include <vector>
#include <unordered_map>
#include <tuple>
#include <type_traits>
#include <typeinfo>
#include <typeindex>

//DirectX Includes
#include <d3d10_1.h>
#include <d3d10.h>
#include <d3d11.h>
#include <d3d11shader.h>
#include <d3dcompiler.h>
#include <d3dcommon.h>

//3rd party Includes
#include "entt/entt.hpp"
#include "fbxsdk.h"
#include "fbxsdk/core/fbxmanager.h"
#include "nlohmann/single_include/nlohmann/json.hpp"