//Generated by premake! Add and/or remove any nessesary includes here!
//Do not remove unless you want to regenerate the default precompile header!
#pragma once

#define NOMINMAX

//Standard Library includes
#include <filesystem>
#include <iostream>
#include <string>
#include <string_view>
#include <cmath>
#include <functional>
#include <vector>
#include <unordered_map>
#include <tuple>
#include <type_traits>
#include <typeinfo>
#include <typeindex>

//DirectX Includes
#include <d3d10_1.h>
#include <d3d10.h>
#include <d3d11.h>
#include <d3d11shader.h>
#include <d3dcompiler.h>
#include <d3dcommon.h>

//3rd party Includes
#include "entt/single_include/entt/entt.hpp"
#include "imgui/imgui.h"
#include "imgui/backends/imgui_impl_dx11.h"
#include "imgui/backends/imgui_impl_win32.h"
#include "imguizmo/ImGuizmo.h"